name: Publish

on: [ push ]

concurrency: ci-${{ github.ref }}

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Publish to Maven repository
        uses: uTen2c/publish-to-github@v1.2
        with:
          publish-path: ${{ github.workspace }}/build/repo
          publish-task: fabric:publish
          repo: ${{ secrets.REPO }}
          token-user: ${{ secrets.TOKEN_USER }}
          token: ${{ secrets.TOKEN }}
